config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'
  resources :sessions
  resources :users

  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#create', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :projects do
        resources :pmaterials
        resources :steps
        resources :user_projects
      end
      resources :users do
        resources :umaterials
        resources :user_projects
      end
      resources :materials
    end
  end

end

app/views/layouts/_header.html.erb
<header id="header" class="page-topbar">
  <div className="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo right">Workbench</a>
        <ul>
          <li><a class="dropdown-button" data-beloworigin="true" data-constrainwidth="false" href="#!" data-activates="dropdownNav"><i class="material-icons">list</i></a></li>
        </ul>
      </div>


    </nav>
  </div>
      <ul id="dropdownNav" class="dropdown-content">
          <li><a href="/">All projects</a></li>
          <li class="divider"></li>
        <% if !session[:user_id] %>
          <li><%= link_to "Login", login_path %></li>
          <li class="divider"></li>
        <% else %>
          <li><%= link_to "#{User.find(session[:user_id]).name}'s Profile", user_path(session[:user_id]) %></li>
          <li class="divider"></li>
        <% end%>
        <%if !user_signed_in?%>
          <li><%= link_to "Register", signup_path %></li>
          <li class="divider"></li>
        <%end%>
        <% if user_signed_in? %>
          <li><%= link_to "Logout", logout_path %></li>
          <li class="divider"></li>
        <%end%>
      </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workbench</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<%= yield %>

</body>
</html>